update dysk script

diff --git a/linux/flexvolume/dysk/dysk b/linux/flexvolume/dysk/dysk
--- a/linux/flexvolume/dysk/dysk
+++ b/linux/flexvolume/dysk/dysk
@@ -20,13 +20,13 @@
 #  - Please install "jq" package before using this driver.
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
 JQ="/usr/bin/jq"
+ERRORLOG="/tmp/dysk.err.log"
 
 usage() {
 	err "Invalid usage. Usage: "
 	err "\t$0 init"
-	err "\t$0 mount <mount dir> <mount device> <json params>"
+	err "\t$0 mount <mount dir> <json params>"
 	err "\t$0 unmount <mount dir>"
 	exit 1
 }
@@ -46,7 +46,6 @@ ismounted() {
 
 mount() {
 	MNTPATH="$1"
-	VOLUME_SRC=$(echo "$2"|"$JQ" -r '.source')
 	ACCOUNTNAME=$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/accountname"] // empty'|base64 -d)
 	ACCOUNTKEY=$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/accountkey"] // empty'|base64 -d)
 	#READ_MODE=$(echo "$2"|"$JQ" -r '.["kubernetes.io/readwrite"]')
@@ -57,18 +56,28 @@ mount() {
 		exit 0
 	fi
 
-	mkdir -p ${MNTPATH} &> /dev/null
+	mkdir -p ${MNTPATH} >/dev/null 2>$ERRORLOG
 
-	result=`/bin/dyskctl mount auto-create -a "${ACCOUNTNAME}" -k "${ACCOUNTKEY}" 2>/dev/null`
+	result=`dyskctl mount auto-create -a "${ACCOUNTNAME}" -k "${ACCOUNTKEY}" 2>"${ERRORLOG}"`
 	diskname=`echo $result | "jq" -r '.Name'`
-	if [ ${#diskname} -gt 4 ]; then
-		#echo /dev/$diskname
-		mkfs.ext4 /dev/$diskname
+	if [ ${#diskname} -lt 5 ]; then
+		errorLog=`cat "${ERRORLOG}"`
+		err '{ "status": "Failure", "message": "Failed to dyskctl mount auto-create, mountPath:'${MNTPATH}', accountname:'${ACCOUNTNAME}', error log:'${errorLog}''
+		exit 1
 	fi
-	/bin/mount "${VOLUME_SRC}" "${MNTPATH}" > /dev/null
-
+	
+	#TODO make fileType(ext4) as a parameter
+	mkfs.ext4 /dev/$diskname >/dev/null 2>$ERRORLOG
 	if [ $? -ne 0 ]; then
-		err '{ "status": "Failure", "message": "Failed to mount device '${DMDEV}' at '${MNTPATH}' , user: '${USERNAME}' , '${VOLUME_SRC}'"}'
+		errorLog=`cat "${ERRORLOG}"`
+		err '{ "status": "Failure", "message": "Failed to format device /dev/$'${diskname}', mountPath:'${MNTPATH}', accountname:'${ACCOUNTNAME}', error log:'${errorLog}''
+		exit 1
+	fi
+	
+	mount /dev/$diskname "${MNTPATH}" >/dev/null 2>$ERRORLOG
+	if [ $? -ne 0 ]; then
+		errorLog=`cat "${ERRORLOG}"`
+		err '{ "status": "Failure", "message": "Failed to mount device /dev/$'${diskname}' at '${MNTPATH}', accountname:'${ACCOUNTNAME}', error log:'${errorLog}''
 		exit 1
 	fi
 	log '{"status": "Success"}'
@@ -82,14 +91,34 @@ unmount() {
 		exit 0
 	fi
 	
-	#TODO: need to find the disk name and run dyskctl unmount -d diskname
-	umount "${MNTPATH}" &> /dev/null
-	if [ $? -ne 0 ]; then
-		err '{ "status": "Failed", "message": "Failed to unmount volume at '${MNTPATH}'"}'
+	#find device name
+	devname=`findmnt -n ${MNTPATH} 2>/dev/null -J | "$JQ" -r '.filesystems' | "$JQ" '.[0]' | "$JQ" -r '.source'`
+	if [ ${#devname} -lt 5 ]; then
+		err '{ "status": "Failure", "message": "Failed to find device name according to mountPath: '${MNTPATH}', returned device name: '${devname}''
 		exit 1
 	fi
-	rmdir "${MNTPATH}" &> /dev/null
+	
+	diskname=`echo $diskname | cut -d'/' -f3`
+	if [ ${#devname} -lt 5 ]; then
+		err '{ "status": "Failure", "message": "Failed to parse disk name according to mountPath: '${MNTPATH}', returned disk name: '${devname}''
+		exit 1
+	fi	
+	
+	umount "${MNTPATH}" >/dev/null 2>$ERRORLOG
+	if [ $? -ne 0 ]; then
+		errorLog=`cat "${ERRORLOG}"`
+		err '{ "status": "Failed", "message": "Failed to unmount volume at '${MNTPATH}'"}, error log:'${errorLog}''
+		exit 1
+	fi
+	rmdir "${MNTPATH}" >/dev/null 2>$ERRORLOG
 
+	dyskctl unmount -d $diskname >/dev/null 2>$ERRORLOG
+	if [ $? -ne 0 ]; then
+		errorLog=`cat "${ERRORLOG}"`
+		err '{ "status": "Failed", "message": "Failed to dyskctl unmount disk('${diskname}')", error log: '${errorLog}'}, error log:'${errorLog}''
+		exit 1
+	fi	
+	
 	log '{"status": "Success"}'
 	exit 0
 }
