update dysk script

diff --git a/linux/flexvolume/dysk/dysk b/linux/flexvolume/dysk/dysk
--- a/linux/flexvolume/dysk/dysk
+++ b/linux/flexvolume/dysk/dysk
@@ -8,7 +8,7 @@
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
-#     http://www.apache.org/licenses/LICENSE-2.0
+#	 http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
@@ -46,65 +46,72 @@ ismounted() {
 
 mount() {
 	MNTPATH="$1"
-        VOLUME_SRC=$(echo "$2"|"$JQ" -r '.source')
-        READ_MODE=$(echo "$2"|"$JQ" -r '.["kubernetes.io/readwrite"]')
-        MOUNT_OPTIONS=$(echo "$2"|"$JQ" -r '.mountOptions // empty')
-        USERNAME=$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/username"] // empty'|base64 -d)
-        PASSWORD=$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/password"] // empty'|base64 -d)
-        
-        if ismounted ; then
-                log '{"status": "Success"}'
-                exit 0
-        fi
+	VOLUME_SRC=$(echo "$2"|"$JQ" -r '.source')
+	ACCOUNTNAME=$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/accountname"] // empty'|base64 -d)
+	ACCOUNTKEY=$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/accountkey"] // empty'|base64 -d)
+	#READ_MODE=$(echo "$2"|"$JQ" -r '.["kubernetes.io/readwrite"]')
+	#MOUNT_OPTIONS=$(echo "$2"|"$JQ" -r '.mountOptions // empty')
+		
+	if ismounted ; then
+		log '{"status": "Success"}'
+		exit 0
+	fi
 
-        mkdir -p ${MNTPATH} &> /dev/null
+	mkdir -p ${MNTPATH} &> /dev/null
 
-        /bin/dyskctl mount auto-create "${VOLUME_SRC}" "${MNTPATH}" -a "${USERNAME}" -k "${PASSWORD}" > /dev/null
+	result=`/bin/dyskctl mount auto-create -a "${ACCOUNTNAME}" -k "${ACCOUNTKEY}" 2>/dev/null`
+	diskname=`echo $result | "jq" -r '.Name'`
+	if [ ${#diskname} -gt 4 ]; then
+		#echo /dev/$diskname
+		mkfs.ext4 /dev/$diskname
+	fi
+	/bin/mount "${VOLUME_SRC}" "${MNTPATH}" > /dev/null
 
-        if [ $? -ne 0 ]; then
-                err '{ "status": "Failure", "message": "Failed to mount device '${DMDEV}' at '${MNTPATH}' , user: '${USERNAME}' , '${VOLUME_SRC}'"}'
-                exit 1
-        fi
-        log '{"status": "Success"}'
-        exit 0
+	if [ $? -ne 0 ]; then
+		err '{ "status": "Failure", "message": "Failed to mount device '${DMDEV}' at '${MNTPATH}' , user: '${USERNAME}' , '${VOLUME_SRC}'"}'
+		exit 1
+	fi
+	log '{"status": "Success"}'
+	exit 0
 }
 
 unmount() {
-        MNTPATH="$1"
-        if ! ismounted ; then
-                log '{"status": "Success"}'
-                exit 0
-        fi
+	MNTPATH="$1"
+	if ! ismounted ; then
+		log '{"status": "Success"}'
+		exit 0
+	fi
+	
+	#TODO: need to find the disk name and run dyskctl unmount -d diskname
+	umount "${MNTPATH}" &> /dev/null
+	if [ $? -ne 0 ]; then
+		err '{ "status": "Failed", "message": "Failed to unmount volume at '${MNTPATH}'"}'
+		exit 1
+	fi
+	rmdir "${MNTPATH}" &> /dev/null
 
-        umount "${MNTPATH}" &> /dev/null
-        if [ $? -ne 0 ]; then
-                err '{ "status": "Failed", "message": "Failed to unmount volume at '${MNTPATH}'"}'
-                exit 1
-        fi
-        rmdir "${MNTPATH}" &> /dev/null
-
-        log '{"status": "Success"}'
-        exit 0
+	log '{"status": "Success"}'
+	exit 0
 }
 
 op=$1
 
 if [ "$op" = "init" ]; then
-        log '{"status": "Success", "capabilities": {"attach": false}}'
-        exit 0
+	log '{"status": "Success", "capabilities": {"attach": false}}'
+	exit 0
 fi
 
 if [ $# -lt 2 ]; then
-        usage
+	usage
 fi
 
 shift
 
 case "$op" in
-        mount)
-                mount $*
-                ;;			
-        unmount)
+	mount)
+		mount $*
+		;;			
+	unmount)
 		unmount $*
 		;;
 	*)
